### ISSUE TITLE
Dual licence is awkward

### ISSUE THREAD

**Issue by hikari-no-yume** [rpjohnst/dejavu#48]
Hi! I am very interested in this project, it's essentially something I've wanted to make myself for years but never actually did. 

I am a bit confused by the licensing choice though. I am familiar with the MIT licence and the Apache licence, but they seem like a bit of an awkward combination to me.

Firstly, they're both liberal non-copyleft licences, so it seems a bit redundant: why not just pick one or the other? I think you could in fact pick MIT and later relicence to both due to how liberal MIT is.

But the main thing that bothers me is that Apache has an annoying terms that require contributors to add comments to every file:

>       (b) You must cause any modified files to carry prominent notices
>          stating that You changed the files; and

I don't think this project complies with this right now. To be honest, probably lots of projects using the licence don't. But I think it's good to be at least a little careful with complying with licences.

I would be grateful to know your thoughts. Mostly, I am just curious why this choice was made!

**Comment by rpjohnst** [comment]
Hi, welcome!

The license choice is a habit I picked up from the Rust ecosystem. The general idea is that users can pick MIT, since it's really simple and compatible with other licenses like GPL; while contributors must comply with Apache, which gives the users (and the project) a bit more safety from things like patent infringement lawsuits. Or rather, I am not a lawyer but that is the intent. 🙂

You're right about the license headers, though I was under the impression they were optional? (Just from that clause you quoted I would expect that to apply more to fork-like scenarios... but again IANAL so 🤷‍♀️) We can always add them if it turns out they are important to someone's use case, but for now I am comfortable with the way things are.
